server:
  port: 9999

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-registration
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  spring:
    security:
      oauth2:
        authorizationserver:
          client:
            oidc-client:
              registration:
                client-id: "oidc-client"
                client-secret: ${OAUTH_SECRET}
                client-authentication-methods:
                  - "client_secret_basic"
                authorization-grant-types:
                  - "authorization_code"
                  - "refresh_token"
                redirect-uris:
                  - "http://127.0.0.1:8088/login/oauth2/code/oidc-client"
                post-logout-redirect-uris:
                  - "http://127.0.0.1:8088/authorized"
                scopes:
                  - "openid"
                  - "profile"
              require-authorization-consent: true
              provider:
                spring:
                  issuer-uri: http://auth-server:9999